from django.db import models
class Countries(models.TextChoices):
    Amazonas = 'Amazonas',
    Áncash = 'Áncash',
    Apurímac = 'Apurímac',
    Arequipa = 'Arequipa'
    Ayacucho = 'Ayacucho',
    Cajamarca = 'Cajamarca',
    Callao = 'Callao',
    Cusco = 'Cusco',
    Huancavelica = 'Huancavelica',
    Huánuco = 'Huánuco',
    Ica = 'Ica',
    Junín = 'Junín',
    LaLibertad = 'La Libertad',
    Lambayeque = 'Lambayeque',
    Lima = 'Lima',
    Loreto = 'Loreto',
    MadredeDios = 'Madre de Dios',
    Moquegua = 'Moquegua',
    Pasco = 'Pasco',
    Piura = 'Piura',
    Puno = 'Puno',
    SanMartín = 'San Martín',
    Tacna = 'Tacna',
    Tumbes = 'Tumbes',
    Ucayali = 'Ucayali',
