# Generated by Django 4.0.4 on 2022-06-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('No Procesado', 'Not Processed'), ('Procesado', 'Processed'), ('Enviado', 'Shipping'), ('Entregado', 'Delivered'), ('Cancelado', 'Cancelled')], default='No Procesado', max_length=50),
        ),
    ]
