# Generated by Django 4.0.4 on 2022-06-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
