# Generated by Django 4.0.4 on 2022-06-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='enterprise',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
